### ISSUE TITLE
Project rename

### ISSUE THREAD

**Issue by cbdevnet** [cbdevnet/midimonster#29]
Some users have remarked that the name `MIDIMonster` is not really indicative of the scope of the project anymore.

What began as a simple MIDI-to-MIDI conversion tool evolved into a full-fledged multi-protocol programmable translation engine.

This issue will be used to track possible new names for the project.

So far, my favorite up until now would be

* `protomonster`

But I'm very open to suggestions.

**Comment by Spacelord09** [comment]
"transmonster" or "translatormonster"

**Comment by Spacelord09** [comment]
I think "protomonster" does'nt say: I'm a multi protocol translator.

**Comment by Spacelord09** [comment]
Or "protolatormonster"

**Comment by cbdevnet** [comment]
Hm, I'd like to keep the name rather short (lets say less than 5 syllables as a somewhat arbitrary limit), `protolatormonster` feels a bit long.

I'm also not dead set on keeping the `-monster` suffix (though I kind of like it for some reason and it _is_ somewhat distinctive).

`transmonster` I think would cause offence to some people though

**Comment by Spacelord09** [comment]
I think then "protomonster" is the best!

**Comment by cbdevnet** [comment]
While this is not a high-priority item, I'm still open to suggestions.

**Comment by phedders** [comment]
Its got lots of arms... or legs. So obviously it should be called...


Midipede!

**Comment by phedders** [comment]
or protoplier

**Comment by Spacelord09** [comment]
Hey @phedders,

Can you explain your thoughts to this names?

**Comment by phedders** [comment]
midipede:
  - MIDI(obvious :)
  - PEDE as in centipede or milipede has many legs - whereas this software has many procols)

protoplier or protoplyer:
   Drops the midi from the name - but focuses on
   - many PROTOcols supported
   - routes beween any - being the multiPLIER between many sources and desintations 

protoplyr:
   As above - but many folks in tech are just plain lazy :)

**Comment by julipatrusheva** [comment]
I love the feeling of associating the product with a monster. It gives me a feeling of power. I'd love to keep it.
On the other side, there is a "translate". To change the word to "Convert" is probably wrong, because of different context. So.. As a result:

- T-Monster (TMonster)
- Transtor 
- Transter - wird automatisch korrigiert als Fehler ins "Trans**F**er"
- TMster (however, when pronouncing this word - you hear "Team")
- @cbdevnet , I liked the idea with **Transmonster**. How it sounds. But I see the issue with the misunderstanding and wrong addressing of the product.
- @Spacelord09 , **protomonster** - As for me it does not look good, and I do not have a feeling wanting to read that. Maybe because of such an amount of **O** .. and, that its all written in lower case.. Hm .. 

Curious, what you think on all of that.
Gonna write if I get some new ideas.

**Comment by Spacelord09** [comment]
-Signaltroll
-MultiMonster

**Comment by cbdevnet** [comment]
Thanks for all the suggestions, but all in all, with some more feedback, a new homepage with a full corporate identity coming up and a v1.0 within reach, I think we're stuck with MIDIMonster, for better or for worse ;)
