### ISSUE TITLE
JACK MIDI/OSC/CV backend

### ISSUE THREAD

**Issue by mxmilkb** [cbdevnet/midimonster#30]
Both JACK and LV2 format have CV signal mechanisms that allow for finer automation than MIDI can support.

carla-git recently introduced internal CV ports, added a CV search filter in the plugin dialog, and will in future expose parameters as CV ports, and zrythm-git has just received CV functionality.

CV support in MIDIMonster would be very handy.

**Comment by cbdevnet** [comment]
Hi, that sounds very interesting indeed! Could you point me to some documentation on the subject? :)

**Comment by mxmilkb** [comment]
In the LV2 spec:
* http://lv2plug.in/ns/lv2core/#CVPort
* https://lac.linuxaudio.org/2015/papers/24.pdf - see section 2.4

Host commits:
* http://git.drobilla.net/cgit.cgi/ingen.git/log/?qt=grep&q=cv
* https://github.com/falkTX/Carla/search?q=cv&type=Commits

Plugins with support:
* https://github.com/blablack/ams-lv2/tree/master/ams.lv2
* https://github.com/harryhaaren/avw.lv2
* http://drobilla.net/software/blop-lv2
* https://github.com/ssj71/infamousPlugins
* http://drobilla.net/software/fomp - some of

If you're on IRC, I'd highly recommend #lad for audio and related dev chat.

**Comment by cbdevnet** [comment]
I'll just do a braindump here for further reference.

So from my reading of the linked specs and then some, the LV2 side would concern only communication between an LV2 plugin host (such as Carla) and the actual plugin.

Since I don't think the MIDIMonster should become a full-blown LV2 plugin host (I'd rather keep with only dealing with control data, not audio, much less realtime audio), we're concerned with how to connect the MIDIMonster to plugin hosts to supply control data.

Now I have not actually used any of these projects (except for a limited JACK setup), as I'm mostly coming from the lighting & show control side of things, but from reading some of the Carla code, it has native support for [OSC control input](https://github.com/falkTX/Carla/blob/develop/source/backend/engine/CarlaEngineOsc.cpp), which is already support by the MIDIMonster, as well as [MIDI control input via JACK](https://github.com/falkTX/Carla/blob/develop/source/backend/engine/CarlaEngineJack.cpp).

There is also somewhat of a non-standard to transmit [OSC via JACK midiports](https://github.com/ventosus/jack_osc), which ingen seems to support but Carla does not. Instead Carla uses JACK ports to transfer CV data (the format of which I don't yet fully understand, but from reading [a note on the JACK homepage](https://jackaudio.org/metadata/signal-type/) it might actually just be DC offset samples at audio rate).

A generic plugin adapting MIDIMonster data to JACK ports (MIDI, MIDI/OSC, CV) would probably be the best interface for these use cases.

**Comment by mxmilkb** [comment]
See also [this thread](https://github.com/OpenMusicKontrollers/synthpod/issues/46) in relation to CV and the synthpod host.

Also, a wee note that there have been newer and alternative [JACK+OSC developments](https://github.com/jackaudio/jack2/pull/514).

**Comment by cbdevnet** [comment]
So from reading a lot of ingen code, it seems the CV data transported via JACK audio ports consists of float32 samples, what I'm currently missing is some kind of upper/lower limit for the values, or any info on how they are interpreted by the plugins themselves.

**Comment by cbdevnet** [comment]
At least on the LV2 plugin side, this seems to be set by the Host as (properties on the incoming port)[http://lv2plug.in/ns/lv2core/#CVPort](?).

**Comment by mxmilkb** [comment]
It appears the various (older) plugins that I linked to above are -1 min to 1 max. 

@falktx noted in #jack earlier: "there is no predefined range. we usually just go with 1.0f = 1v".

I think that comment relates to the newer [MOD CV plugins](https://forum.moddevices.com/t/cv-plugins-are-here/3454/5). I don't think those are openly available yet though(?). I guess they use the Eurorack/VCV convention of 0 to 10 for unipolar / -5 to 5 for bipolar. Awaiting confirmation on that.

**Comment by mxmilkb** [comment]
falkTX says there is no convention among the newer MOD CV plugins. They will be GPLd after getting free artwork.

**Comment by drobilla** [comment]
LV2 CV ports are just like control ports as far as values go, the _plugin_ defines a [minimum](http://lv2plug.in/ns/lv2core#minimum), [maximum](http://lv2plug.in/ns/lv2core#maximum) and [default](http://lv2plug.in/ns/lv2core#default) value.

**Comment by cbdevnet** [comment]
Thanks for the feedback, so I gather the values are unitless (and dimensionless) until they arrive at the plugin itself.

I'll just make the range configurable in the backend instance configuration :)

**Comment by cbdevnet** [comment]
I just pushed an implementation that seems to work for my test cases, though I have only tested with basic MIDI and CV transport yet. I may look into setting up a basic LV2 setup some time, but any feedback would be much appreciated :)

**Comment by cbdevnet** [comment]
Marking this issue closed, as the backend is implemented and seems to do it's job, but further discussion is welcome :)
