### ISSUE TITLE
Local sACN Input does not work on Windows

### ISSUE THREAD

**Issue by nklz** [cbdevnet/midimonster#39]
Using the config
```
[backend sacn]
bind = 0.0.0.0

[backend winmidi]

[sacn in]
universe = 1

[winmidi out]
write = LoopBe Internal MIDI

[map]
in.{1..100} >  out.ch0.note.{1..100}
```
no output is generated on the MIDI device.

The problem is probably the sACN Input as i tested:
- MIDI Notes -> sACN Output - works
- sACN Input -> sACN Output - doesn't work, only 0x00 values transmitted
- sACN Input -> MIDI Notes - doesn't work, no notes sent

I didn't have a look at the code yet, so I don't know what the reason might be. I am using a freshly compiled version from master. sACN was transmitted (locally) from sACN Viewer or GrandMA2, both do not work.

**Comment by nklz** [comment]
Addition: problem only occurs when the sACN data is transmitted on the same device MIDIMonster runs on.

**Comment by cbdevnet** [comment]
Hi @nklz, thanks for the report! I'll try to reproduce the problem, receiving multicast data on loopback is a tricky thing ;)

**Comment by cbdevnet** [comment]
I'd guess it's at least partly related to the backend library unsetting `IP_MULTICAST_LOOP` on mcast/bcast sockets (https://github.com/cbdevnet/midimonster/blob/master/backends/libmmbackend.c#L90).

This is done so the backend does not have to filter out it's own packets on the input side again, to allow both input and output on the same universe at the same time (which is probably not something many people do, since sACN is usually used in a unidirectional mode, if possibly with multiple masters). When enabling `IP_MULTICAST_LOOP` on the FD's used for sACN, every output value also generates input events on the instance and other clients on the same host can read the output (tested on Linux only so far).

I'll think about making this configurable via a backend `bind` option.

**Comment by cbdevnet** [comment]
Please check whether adding `local` to the bind configuration offers some improvements :)

**Comment by cbdevnet** [comment]
Verified working. The configuration used was

```
[winmidi lc]
write = Launch

[backend sacn]
bind = 0.0.0.0 5568 local

[sacn in]
universe = 1

[map]
in.{1..8} > lc.ch0.note{0..7}
```

Running sACNView on the same host, generating output on Universe 1 lights up the buttons on the Launch Control.

Please reopen if I misunderstood your use case :)
