### ISSUE TITLE
[sACN] Failed to output universe discovery frame for interface 0: no error

### ISSUE THREAD

**Issue by JoMen6** [cbdevnet/midimonster#45]
@cbdevnet thank you for this awesome project :fire:

I configure midimonster to convert winMidi to sACN similar to the documentation and it work with network connection on windows machine. But when I try it offline i got the following error message: 

**[sACN] Failed to output universe discovery frame for interface 0: no error**

Is there a possible workaround thats works offline?

**Comment by Spacelord09** [comment]
@JoMen6 What do you mean with offline?

**Comment by JoMen6** [comment]
A laptop without wifi or lan connection.

**Comment by Spacelord09** [comment]
@JoMen6 Can you explain your usecase?

**Comment by Spacelord09** [comment]
If you want to output the sACN backend to a software on your computer you can use the microsoft loopback adapter.

**Comment by cbdevnet** [comment]
Hi, happy that you like the project :)

The error might be because broadcast frames (such as the universe discovery frame) aren't really applicable to loopback interfaces, but I think it should mostly just work (ie, you can safely ignore that specific message). It should not stop the backend from generating data output.

You might try adding the `local` parameter to your `bind` statement, which allows applications on localhost to receive the data frames sent by the MIDIMonster on local interfaces.

**Comment by JoMen6** [comment]
Thanks for the quick replys the microsoft loopback adapter works like a charm 👍
