### ISSUE TITLE
[windows] select failed: Result too large

### ISSUE THREAD

**Issue by Arkenklo** [cbdevnet/midimonster#51]
When running midimonster v0.3 on Windows 10, the following output is produced;
```
C:\Users\root\Dropbox\Apps\midimonster-v0.3-windows>midimonster.exe
Registered backend maweb
select failed: Result too large
maweb   Backend shut down
```
Happens regardless of backend and configuration.
I have a couple loopback interfaces already, but otherwise it's a pretty vanilla install.

I'm not a windows guy, so let me know what other info I can supply :)

**Comment by cbdevnet** [comment]
Hi, thanks for taking the time to report this!
The error message is probably not representative because the code currently takes the value of `errno`, runs that through `strerror()` to get something readable and prints that. Unfortunately on Windows, that doesn't work and we'll have to look at the output of `WSAGetLastError()` and similar. The backend itself has some provisions for Windows-specific socket handling but that particular part of the core doesn't yet.

I'm planning to release a v0.4 in the next few days, I'll add some code to output the correct error message here. I'll also try to reproduce the problem on a Windows machine, then I'll get back to you :)

**Comment by cbdevnet** [comment]
Commit aa5650c77af9379fc80c5329e0c0ffbe1f5d2355 implements printing the correct message on Windows, if you feel comfortable building for yourself you can test right now :)

**Comment by cbdevnet** [comment]
Interestingly, I'm getting a similar error message on my Windows 10 VM when using the default useless config. It seems to work when using a simple ArtNet configuration.

Windows 7 does not seem to have any problems.

I'll investigate further :)

**Comment by cbdevnet** [comment]
I think I found it - it seems that Windows doesn't like it when you call `select()` without any descriptors to wait on. The resulting error message is `An invalid argument was supplied`.

Could you try running the MIDIMonster with the following configuration for a test:

```
[backend artnet]
bind = 0.0.0.0

[artnet art]
destination = 255.255.255.255

[loopback loop]

[map]
loop.test > art.1
```

That should start up normally

**Comment by Arkenklo** [comment]
Hey! Thank you for the great feedback!
I'm away from my Windows box right now, but I'll verify the new build and the config you gave next week :)

**Comment by cbdevnet** [comment]
Please retest with v0.5 and reopen if the problem persists
