### ISSUE TITLE
sysex

### ISSUE THREAD

**Issue by AlexFundorin** [cbdevnet/midimonster#6]
Is there sysex support in this app? I didn't find any mentions.
Is it possible to parse osc commands, based on the script logic, before generating midi commands?

**Comment by cbdevnet** [comment]
Hi, and thanks for your interest!

In principle this could be added to the codebase (alsa does provide access to sysex messages). Due to the fact that sysex messages are highly unspecified (ie. have no inherent structure other than a common header), configuring them for appropriate handling is a complex matter.

The MIDIMonster primarily concerns itself with the concept of channels (in the case of MIDI, the mapping would be a note or a CC) which can be set to values. That mapping is harder to find and describe for sysex.

What would be possible with relatively few adjustments would be functionality like a sysex channel, which is described by a manufacturer ID, an optional match section (for sysex input) and a data byte offset. When required, this could be extended to include variable length data sections, though that would require additional configuration parameters.

For output, this would require either a complex specification describing the concrete sysex data format to be transmitted, or for a simpler approach, just a prefix data part, the data section specification and a suffix data part.

The second option would probably be pretty easy to implement by extending
* The MIDI backend with global configuration storage for sysex channels similar to the OSC backend (Currently, all MIDI channel details are implicitly encoded within the 64bit channel ID via the midi_channel_ident structure/union)
* (`midi_configure_instance`)[https://github.com/cbdevnet/midimonster/blob/master/midi.c#L89] with configuration for the sysex format (the OSC backend may serve as an example here) and the functionality to store it into configuration
*(`midi_channel`)[https://github.com/cbdevnet/midimonster/blob/master/midi.c#L116] with the functionality to recognize and map to backend-global data storage a sysex channel specifier
*(`midi_set`)[https://github.com/cbdevnet/midimonster/blob/master/midi.c#L163] with the functionality to output sysex messages by building byte-strings from the global configuration and channel value
*(`midi_handle`)[https://github.com/cbdevnet/midimonster/blob/master/midi.c#L199] with a (limited) parser based on the configuration to recover the value part from the sysex message

I hope this is of help to you! If you are interested in implementing this functionality, I would be happy to answer any further questions to the best of my ability. My primary purpose with this project is to map the basic channels of the various protocols, but I'm open to extensions!

**Comment by AlexFundorin** [comment]
First of all, thank you for your detailed answer.
I should've mention the specific task, for which I need such bridge.
I have Novation SL MkII midi controller with faders, pots, encoders, LEDs and LCD.
I also have programmers manual with all it's commands described, such as how to construct sysex message to display info on LCD or CC numbers to light LEDs.
The DAW that I'm using is called Reaper. It can be operated via OSC commands. It also can send varous data and feedback via OSC protocol. I have a full list of Reaper's OSC commands and their format (float, boolean, string, etc).
What I need is some middleware app that could sit in the tray convert midi<>osc, based on some rules that one create (not direct command conversion). 
I also forgot to mention, that I'm using Windows on the music machine, so, no ALSA for me.

I've tried many apps, oscii-bot, Ctrlr, VSTLua, pd, processing, Bidule, Usine Hollyhock and many others. Nonу of them was stable/functional/simple enough to perform this task. I was hoping that midimonster might be the right tool for it.

**Comment by cbdevnet** [comment]
Ah OK, that helps understand your use case quite a bit!

LCD screens could be tricky in that OSC strings are currently entirely unsupported because they do not map neatly onto the channel concept (only the various integer and floating point formats of OSC are currently understood by the MIDIMonster).
Lighting LEDs (which should at the most complex be dimming via floats) is possible if they are controlled via the normal MIDI capabilities (Notes & CCs) - tested on Launchpad, Launch Control and some AKAI thingy.

Free-form rule-based translation is alas not within the realm of the MIDIMonster, only in the very limited sense that the channel abstraction provides.

A secondary problem that would be the Windows platform - while most of the MIDIMonster is platform independent, unfortunately the MIDI backend is not, due to the lack of a consistent API across systems. A MIDI backend for Windows would have to be implemented from scratch. However, if you have access to a Linux machine on the same network, where you could attach the MIDI controller, that could be sidestepped (as OSC is "just" network)

**Comment by AlexFundorin** [comment]
Yeah. Totally understand. Ctrlr was also having problems with string types.
I could run linux on virtual machine, but it seems kinda opposite to the "small tray utility". 😉 
Anyway, thank you for your time. Appreciate it.

**Comment by cbdevnet** [comment]
Thanks for your interest - I'll close the issue then, but I'll think about your use case and if in the future something like this is implemented, I'll be sure to ping you!
