### ISSUE TITLE
lua without default handler 

### ISSUE THREAD

**Issue by GralfR** [cbdevnet/midimonster#75]
Hi!

I'm just learning the lua backend. My first script is easy:
```
function echo(value)
    print("in"..input_channel().."="..value)
end
```
My config is setup to use that script and the function echo is the default-handler.
A mapping like lua.{1..8} is working fine.

Now, I'd like to use several functions inside the script and use one or another for several events. So, I removed the definition of the default-handler and tried to call the function echo() as a handler inside the mapping like:
`foo.bar{1..8} > lua.echo{1..8}`
instead of 
`foo.bar{1..8} > lua.{1..8}`

This is not working.
How do I have to map to a function inside the script, which is not the default-handler? I'd like to do something like
```
foo.ch{1..8} > lua.echoA{1..8}
bar.ch{1..8} > lua.echoB{1..8}
```
means different inputs should be mapped to different functions and handled differently inside the same script. Is this possible? What's the syntax? The lua backend documentation was not helpful.

Or the other way: how to use a default-handler and use more than one parameter?
```
function echo(foo,bar)
  print(foo.."="..bar)
end
```
What's the syntax for that inside the mapping?

thanks

**Comment by cbdevnet** [comment]
Hi @GralfR, thanks for the question, I will try to extend the Lua documentation based on this.

To answer your question, there is currently no method for mapping a function with multiple parameters (the only parameter is always the current event value), but you can access the name of the channel the current value belongs to using the `input_channel()` function. So in your `echo` default handler, you could do

```lua
function echo(value)
  print(input_channel().."="..value)
end
```

As for why mapping `foo.bar{1..8} > lua.echo{1..8}` does not work, the reason is that this maps channels `foo.bar1` to `foo.bar8` to the Lua functions `lua.echo1` through `lua.echo8`, so you would either need to create eight Lua functions like so

```lua
function echo1(value)
   -- handle value here
end
```

or create a default handler the "hard way", by assigning the individual channel handler functions to your echo function like so

```lua

function echo(value)
  print(input_channel().."="..value)
end

echo1 = echo
echo2 = echo
[...]
```

**Comment by GralfR** [comment]
Hi!
Thanks for making clear the way the handler works.
I now do it like
`foo.bar{1..8} > lua.echo.{1..8}`
Inside my handler I split the input_channel() at the dot and branch depending on the value. This keeps mapping readable.
