### ISSUE TITLE
Option for disabling ArtNet rate limiting

### ISSUE THREAD

**Issue by djkad** [cbdevnet/midimonster#77]
It seems like some midi messages are lost while sending to artnet. Main question is: Do Midimonster use multithreads/multiprocess communication ?

**Comment by cbdevnet** [comment]
Hi @djkad, thanks for your interest in the MIDIMonster.

The MIDIMonster currently only uses Multithreading in some backends where the interfaced APIs require it. This mostly concerns the `winmidi` and `jack` backends.

For the `artnet` backend, messages may be lost due to the rate limiting imposed by the protocol specification (Section `Refresh rate` in the [ArtNet spec](https://artisticlicence.com/WebSiteMaster/User%20Guides/art-net.pdf), which limits the rate of transmitted packets to the network. Events will be coalesced (ie., the latest available value at the next transmission point will be used). This limit is common to both ArtNet and sACN, it can be disabled on sACN instances using the `realtime` option.

I will look into implementing this flag for the `artnet` backend, too.

**Comment by djkad** [comment]
Thank you a lot. 
If possible I would evict to buy a dmxis or other interfaces☺

**Comment by cbdevnet** [comment]
For further reference, this will require an additional instance configuration parameter for the ArtNet backend as well as changes to the rate-limiting logic in https://github.com/cbdevnet/midimonster/blob/master/backends/artnet.c#L304, allowing the flag to bypass the limiter.
