### ISSUE TITLE
Suggestion / Enhancement for winmidi.dll

### ISSUE THREAD

**Issue by hellishvictor** [cbdevnet/midimonster#81]
Hi, when is used the name of the midi port instead of a number (f.e.: read = "loopMIDI Port 1"), its showed again after the ID number, which is not really necessary and just make the line longer without sense:

**winmidi Selected input device loopMIDI Port 1 (ID 0) for name loopMIDI Port 1
winmidi Selected output device loopMIDI Port 2 (ID 2 for name loopMIDI Port 2**

Also, notice that on the output line a parenthesis is missed after the ID number.
It will look better like this:

**winmidi Selected input device loopMIDI Port 1 (ID 0)
winmidi Selected output device loopMIDI Port 2 (ID 2)**

In case you considered to apply those changes, those lines belong to the "winmidi.dll", which on the source are on the file "winmidi.c":

_Line 391 (for input):_
			LOGPF("Selected input device %s (ID %" PRIsize_t ") for name %s", input_caps.szPname, n, prefix);
-> modified:
			LOGPF("Selected input device %s (ID %" PRIsize_t ")", n, prefix);

_Line 424 (for output):_
			LOGPF("Selected output device %s (ID %" PRIsize_t " for name %s", output_caps.szPname, n, prefix);
-> modified:
			LOGPF("Selected output device %s (ID %" PRIsize_t ")", n, prefix);

I'm not sure if the ",n, prefix" should be omitted, so I leave it there (I just did the changes to the file with WinHex since I don't know how to compile the source code).

Cheers.

**Comment by cbdevnet** [comment]
Hi @hellishvictor,
the output format is displaying the name twice because it is possible to use the `read` and `write` instance configuration options with "prefix matching". What that means is that you can just enter the first few characters or words of the port name instead of the whole name (for example, if you don't know it by hear. I often use just `Launch Control` as port name and let the MIDIMonster select the correct one).

The output in this case tells you what exact device was matched for the selection.

**Comment by hellishvictor** [comment]
Awesome. Thank you for the detailed explanation.

**Comment by hellishvictor** [comment]
Please, release a new version with those changes applied; the v0.5 is from 27 Apr 2020, one year old.

**Comment by Spacelord09** [comment]
Hello @hellishvictor,
That's right. We are currently working on the next release.
unfortunately we can't give an eta for the 1.0 release, due to @cbdevnet has little time at the moment.

In the meantime you can build your own version of the MIDIMonster,
To do so you can find the instructions to use our installer at our Knowledgebase(https://kb.midimonster.net/).
If you have further questions just join our Discord(https://discord.gg/sm8EmZN) or answer here ;)

**Comment by cbdevnet** [comment]
Hi @hellishvictor,

I have a few more changes in my local pipeline which ideally I would like to see in the next release. I do however recognize that the binaries are somewhat lagging behind. Sadly, I currently can't put a lot of time into my open source activities, but be assured that the project is still alive and kicking :)

I have uploaded a current windows development build to https://files.midimonster.net/develop/midimonster-v0.5-72-g71d86ec-windows.zip for your convenience.

**Comment by hellishvictor** [comment]
Thank you very much for the upload, you make my day! :)
