### ISSUE TITLE
Midimonster doesn't prefer shorter prefix matches

### ISSUE THREAD

**Issue by keldu** [cbdevnet/midimonster#85]
The WiiMote registers multiple evdev devices with the main buttons called

"Nintendo Wii Remote"

while the others are called

"Nintendo Wii Remote IR/Accelerometer/Motion Plus"

Using ```input=Nintendo Wii Remote``` currently matches the motion plus evdev device.

Workaround is using the device option, but I'd rather have a more reliable way to write my Wii Remote configs.

**Comment by cbdevnet** [comment]
The name matching code at https://github.com/cbdevnet/midimonster/blob/master/backends/evdev.c#L113 currently checks for the first available prefix match while iterating through the event file descriptors, returning early when a match is found.

One solution would be to add a special indicator (e.g. `!Nintendo Wii Remote`) to indicate exact matching should be used instead, but that might be difficult to understand for people trying to understand the backend.

The other option would be to scan all event file descriptors regardless of whether a match was found, store a "best match" candidate and return that if no exact match is found, the exact match otherwise. The benefit of this solution would be that no additional mental effort is required for writing the configuration.

**Comment by cbdevnet** [comment]
Branch with fixes merged
