### ISSUE TITLE
ArtPollReply to ArtPoll packages

### ISSUE THREAD

**Issue by pekkakoskinen** [cbdevnet/midimonster#95]
Thanks for your great work!

I'm trying to get Midimonster work in my network with other Artnet devices. The problem is that other devices don't "see" midimonster as a artnet device since it doesn't seem to reply ArtPoll discovery packages. The other devices only support sending Artnet data to IPs / devices that respond to ArtPoll packages.

Does or could Midimonster support ArtPollReply packages as a response to ArtPoll packages?

Reference: https://art-net.org.uk/how-it-works/discovery-packets/

**Comment by cbdevnet** [comment]
This ticket is almost complete and the functionality can hopefully be merged in the next few days. Due to some "oddities" in the specification, this had a bit more impact than I expected and will only be supported for IPv4. It also requires some additional configuration options.

Additionally, we have now registered an official ESTA Manufacturer ID (`0x4653`) and an ArtNet OEM code (`0x2B93`) to be used with the ArtPoll functionality
